# Ours
python DHOtrain.py -s data/train/ -m output/train --eval --store_grads --lambda_sh_sparsity=0.1 --store_grads --cull_SH 15000 --std_threshold=0.04 --mercy_points --prune_dead_points --store_grads --lambda_alpha_regul=0.01 --std_threshold=0.04 --cdist_threshold=6 --mercy_type=redundancy_opacity_opacity --lambda_start=0.5 --lambda_end=0.3 --beta=0.05 --gama=0.05 --grad=0.1
python DHOtrain.py -s data/truck/ -m output/truck --eval --store_grads --lambda_sh_sparsity=0.1 --store_grads --cull_SH 15000 --std_threshold=0.04 --mercy_points --prune_dead_points --store_grads --lambda_alpha_regul=0.01 --std_threshold=0.04 --cdist_threshold=6 --mercy_type=redundancy_opacity_opacity --lambda_start=0.5 --lambda_end=0.3 --beta=0.05 --gama=0.05 --grad=0.1
python DHOtrain.py -s data/drjohnson/ -m output/drjohnson --eval --store_grads --lambda_sh_sparsity=0.1 --store_grads --cull_SH 15000 --std_threshold=0.04 --mercy_points --prune_dead_points --store_grads --lambda_alpha_regul=0.01 --std_threshold=0.04 --cdist_threshold=6 --mercy_type=redundancy_opacity_opacity --lambda_start=0.2 --lambda_end=0.1 --beta=0.001 --gama=0.001 --grad=0.1
python DHOtrain.py -s data/playroom/ -m output/playroom --eval --store_grads --lambda_sh_sparsity=0.1 --store_grads --cull_SH 15000 --std_threshold=0.04 --mercy_points --prune_dead_points --store_grads --lambda_alpha_regul=0.01 --std_threshold=0.04 --cdist_threshold=6 --mercy_type=redundancy_opacity_opacity --lambda_start=0.3 --lambda_end=0.1 --beta=0.001 --gama=0.001 --grad=0.1
python DHOtrain.py -s data/bicycle/ -m output/bicycle --eval --store_grads --lambda_sh_sparsity=0.1 --store_grads --cull_SH 15000 --std_threshold=0.04 --mercy_points --prune_dead_points --store_grads --lambda_alpha_regul=0.01 --std_threshold=0.04 --cdist_threshold=6 --mercy_type=redundancy_opacity_opacity --lambda_start=0.3 --lambda_end=0.2 --beta=0.025 --gama=0.025 --grad=0.1
python DHOtrain.py -s data/bonsai/ -m output/bonsai --eval --store_grads --lambda_sh_sparsity=0.1 --store_grads --cull_SH 15000 --std_threshold=0.04 --mercy_points --prune_dead_points --store_grads --lambda_alpha_regul=0.01 --std_threshold=0.04 --cdist_threshold=6 --mercy_type=redundancy_opacity_opacity --lambda_start=0.3 --lambda_end=0.2 --beta=0.001 --gama=0.001 --grad=0.1
python DHOtrain.py -s data/counter/ -m output/counter --eval --store_grads --lambda_sh_sparsity=0.1 --store_grads --cull_SH 15000 --std_threshold=0.04 --mercy_points --prune_dead_points --store_grads --lambda_alpha_regul=0.01 --std_threshold=0.04 --cdist_threshold=6 --mercy_type=redundancy_opacity_opacity --lambda_start=0.3 --lambda_end=0.2 --beta=0.001 --gama=0.001 --grad=0.1
python DHOtrain.py -s data/garden/ -m output/garden --eval --store_grads --lambda_sh_sparsity=0.1 --store_grads --cull_SH 15000 --std_threshold=0.04 --mercy_points --prune_dead_points --store_grads --lambda_alpha_regul=0.01 --std_threshold=0.04 --cdist_threshold=6 --mercy_type=redundancy_opacity_opacity --lambda_start=0.3 --lambda_end=0.2 --beta=0.001 --gama=0.001 --grad=0.1
python DHOtrain.py -s data/kitchen/ -m output/kitchen --eval --store_grads --lambda_sh_sparsity=0.1 --store_grads --cull_SH 15000 --std_threshold=0.04 --mercy_points --prune_dead_points --store_grads --lambda_alpha_regul=0.01 --std_threshold=0.04 --cdist_threshold=6 --mercy_type=redundancy_opacity_opacity --lambda_start=0.3 --lambda_end=0.2 --beta=0.001 --gama=0.001 --grad=0.1
python DHOtrain.py -s data/room/ -m output/room --eval --store_grads --lambda_sh_sparsity=0.1 --store_grads --cull_SH 15000 --std_threshold=0.04 --mercy_points --prune_dead_points --store_grads --lambda_alpha_regul=0.01 --std_threshold=0.04 --cdist_threshold=6 --mercy_type=redundancy_opacity_opacity --lambda_start=0.3 --lambda_end=0.2 --beta=0.001 --gama=0.001 --grad=0.1
python DHOtrain.py -s data/stump/ -m output/stump --eval --store_grads --lambda_sh_sparsity=0.1 --store_grads --cull_SH 15000 --std_threshold=0.04 --mercy_points --prune_dead_points --store_grads --lambda_alpha_regul=0.01 --std_threshold=0.04 --cdist_threshold=6 --mercy_type=redundancy_opacity_opacity --lambda_start=0.3 --lambda_end=0.2 --beta=0.001 --gama=0.001 --grad=0.1
python DHOtrain.py -s data/flowers/ -m output/flowers --eval --store_grads --lambda_sh_sparsity=0.1 --store_grads --cull_SH 15000 --std_threshold=0.04 --mercy_points --prune_dead_points --store_grads --lambda_alpha_regul=0.01 --std_threshold=0.04 --cdist_threshold=6 --mercy_type=redundancy_opacity_opacity --lambda_start=0.3 --lambda_end=0.2 --beta=0.001 --gama=0.001 --grad=0.1
python DHOtrain.py -s data/treehill/ -m output/treehill --eval --store_grads --lambda_sh_sparsity=0.1 --store_grads --cull_SH 15000 --std_threshold=0.04 --mercy_points --prune_dead_points --store_grads --lambda_alpha_regul=0.01 --std_threshold=0.04 --cdist_threshold=6 --mercy_type=redundancy_opacity_opacity --lambda_start=0.3 --lambda_end=0.1 --beta=0.05 --gama=0.05 --grad=0.1